%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: H:\Dropbox\GMRF-SLAM\Code\slam\FeaturesAndLocations.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2014/02/02 18:10:56

%% Import the data
%[~, ~, raw] = xlsread('H:\Dropbox\GMRF-SLAM\Code\slam\FeaturesAndLocations.xlsx','Sheet1','A2:AL464');
[~, ~, raw] = xlsread('C:\Users\dohuan\Documents\GitHub\GP-SLAM\MATLAB\FeaturesAndLocations.xlsx','Sheet1','A2:AL464');

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
velocity = data(:,1);
turnrate = data(:,2);
locationX = data(:,3);
locationY = data(:,4);
time = data(:,5);
jpgfile = data(:,6);
AFFT1 = data(:,7);
% AFFT2 = data(:,8);
% AFFT3 = data(:,9);
% AFFT4 = data(:,10);
% AFFT5 = data(:,11);
% AFFT6 = data(:,12);
% AFFT7 = data(:,13);
% AFFT8 = data(:,14);
% AFFT9 = data(:,15);
% AFFT10 = data(:,16);
% AFFT11 = data(:,17);
% AFFT12 = data(:,18);
% AFFT13 = data(:,19);
% AFFT14 = data(:,20);
% AFFT15 = data(:,21);
% AFFT16 = data(:,22);
% HIST1 = data(:,23);
% HIST2 = data(:,24);
% HIST3 = data(:,25);
% HIST4 = data(:,26);
% HIST5 = data(:,27);
% HIST6 = data(:,28);
% HIST7 = data(:,29);
% HIST8 = data(:,30);
% HIST9 = data(:,31);
% HIST10 = data(:,32);
% HIST11 = data(:,33);
% HIST12 = data(:,34);
% HIST13 = data(:,35);
% HIST14 = data(:,36);
% HIST15 = data(:,37);
% HIST16 = data(:,38);

%% Clear temporary variables
clearvars data raw;